
namespace DataMigration
{
    static class TupleList
    {
        public static List<(int, string, int, string, string)> categoryTupleList;
        public static List<(int, int, string, int, string, string)> subcategoryTupleList;
        static TupleList()
        {
            categoryTupleList = new List<(int, string, int, string, string)>()
            {
                (
                    1,
                    "Nyheder",
                    1,
                    "https://t4.ftcdn.net/jpg/01/67/74/79/360_F_167747932_NE1da5cf9FM30QExtlFjbmk9ypItoJl2.jpg",
                    "Nye varer i butikken"
                ),
                (
                    2,
                    "Stel",
                    2,
                    "https://em-epi-static-prod.azureedge.net/altdk-media/ba1142a50dd241e9801f3e9d466cd314/032d9425aa1e4b81ad0fe32b500d0513.jpg",
                    "Stel"
                ),
                (
                    3,
                    "Figurer",
                    3,
                    "https://gcp-la8-storage-cdn.lot-art.com/public/upl/61/Royal-Copenhagen-og-Bing-and-Grndahl-samling-figurer-af-porcelaen-14_1573590919_3737.jpg",
                    "Figurer"
                ),
                (
                    4,
                    "Smykker",
                    4,
                    "https://images.squarespace-cdn.com/content/v1/5e7da489f524e90512c17a11/4c3f3572-9d83-455d-b50c-d5840146f5bc/smykbar_0318_2.jpg",
                    "Smykker"
                ),
                (
                    5,
                    "Sølv",
                    5,
                    "https://via.ritzau.dk/data/images/00774/deb4519e-e5d8-488b-b7fd-6af804af7519.jpg",
                    "Ædelmetal"
                ),
                (
                    6,
                    "Guld",
                    6,
                    "https://nyfortuna.dk/wp-content/uploads/100gr_Metalor-1-1.jpg",
                    "Ædelmetal"
                ),
                (
                    7,
                    "Bestik",
                    7,
                    "https://royaldesign.dk/image/4/dorre-new-england-bestikst-60-dele-1?w=1366&quality=80",
                    "Flottern"
                ),
                (
                    8,
                    "Keramik / Stentøj",
                    8,
                    "https://www.fof.dk/-/media/images/egne/aarhus/kreative-fag/keramik/1920x960-kompri-og-geo/kompri-geotag/keramik-og-stentoej-1-1920x960-komp-geo.jpg?cx&cy&cw=600&ch=600&hash=7ABE98C5A699BD0F123C06C50CCAB132",
                    "Top dollar"
                ),
                (
                    9,
                    "Platter",
                    9,
                    "https://static.wixstatic.com/media/c38ac4_6942d67c8014403996d80c001be6c9a9~mv2.jpg/v1/fill/w_347,h_462,al_c,q_85,usm_0.66_1.00_0.01/c38ac4_6942d67c8014403996d80c001be6c9a9~mv2.webp",
                    "Top lækkert"
                ),
                (
                    10,
                    "Malerier",
                    10,
                    "https://mynewart.dk/1097-large_default/froggy.jpg",
                    "Niceness"
                ),
                (
                    11,
                    "Lamper",
                    11,
                    "https://images-bonnier.imgix.net/files/bob/production/2022/09/21105513/Koglen-e1663750522448.jpg?auto=format&w=1024&q=60",
                    "Lamper"
                ),
                (
                    12,
                    "Glas",
                    12,
                    "https://shop11399.sfstatic.io/upload_dir/shop/_thumbs/25178.w1220.h1220.fill.png",
                    "Glas"
                ),
                (
                    13,
                    "Købes",
                    13,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                )
        };
            subcategoryTupleList = new List<(int, int, string, int, string, string)>
            {
               (
                1,
                2,
                "Blå Blomst Flettet",
                1,
                "https://via.placeholder.com/600x400",
                "Beskrivelse"
                ),
                (
                    2,
                    2,
                    "Blå Blomst Juliane Marie",
                    2,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    3,
                    2,
                    "Blå Blomst Kantet",
                    3,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    4,
                    2,
                    "Blå Blomst Svejfet",
                    4,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    5,
                    2,
                    "Blå Blomst Svejfet med Guldkant",
                    5,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    6,
                    2,
                    "Blå Buket",
                    6,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    7,
                    2,
                    "Blå Fasan",
                    7,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    8,
                    2,
                    "Blå Rose",
                    8,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    9,
                    2,
                    "Blå Tone",
                    9,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    10,
                    2,
                    "Blå Vifte",
                    10,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    11,
                    2,
                    "Blåmalet",
                    11,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    12,
                    2,
                    "Empire",
                    12,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    13,
                    2,
                    "Fiskestel",
                    13,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    14,
                    2,
                    "Flora Danica",
                    14,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    15,
                    2,
                    "Golden Summer",
                    15,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    16,
                    2,
                    "Grøn Blomst Svejfet",
                    16,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    17,
                    2,
                    "Guld Vifte",
                    17,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    18,
                    2,
                    "Henriette",
                    18,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    19,
                    2,
                    "Konkylie, Hvid",
                    19,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    20,
                    2,
                    "Konkylie, Rosa",
                    20,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    21,
                    2,
                    "Mega Blå",
                    21,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    22,
                    2,
                    "Musselmalet",
                    22,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    23,
                    2,
                    "Musselmalet Halvblonde",
                    23,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    24,
                    2,
                    "Musselmalet Helblonde",
                    24,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    25,
                    2,
                    "Måge med guldkant",
                    25,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    26,
                    2,
                    "Måge uden guldkant",
                    26,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    27,
                    2,
                    "Palmette",
                    27,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    28,
                    2,
                    "Prinsesse",
                    28,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    29,
                    2,
                    "Purpur",
                    29,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    30,
                    2,
                    "Relief",
                    30,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    31,
                    2,
                    "Saksisk Blomst Fuld",
                    31,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    32,
                    2,
                    "Saksisk Blomst Juliane Marie",
                    32,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    33,
                    2,
                    "Saksisk Blomst Let",
                    33,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    34,
                    2,
                    "Skærsommernatsdrøm",
                    34,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    35,
                    2,
                    "Sommerfugl",
                    35,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    36,
                    2,
                    "Sommerfugl Dickens",
                    36,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    37,
                    2,
                    "Sommerfugl Kipling",
                    37,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    38,
                    2,
                    "Stjerneriflet",
                    38,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    39,
                    2,
                    "Tranquebar",
                    39,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    40,
                    2,
                    "Ursula",
                    40,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    41,
                    3,
                    "Royal Copenhagen",
                    1,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    42,
                    3,
                    "B&G",
                    2,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    43,
                    3,
                    "Dahl Jensen",
                    3,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    44,
                    3,
                    "Lyngby",
                    4,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    45,
                    3,
                    "Bjørne",
                    5,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    46,
                    3,
                    "Fugle",
                    6,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    47,
                    3,
                    "Hunde",
                    7,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    48,
                    3,
                    "Katte",
                    8,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    49,
                    3,
                    "Andre dyr",
                    9,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    50,
                    3,
                    "Faun",
                    10,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    51,
                    3,
                    "Håndværkere",
                    11,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    52,
                    3,
                    "Menneske-figurer",
                    12,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    53,
                    3,
                    "Stentøj figurer",
                    13,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    54,
                    3,
                    "Aluminia",
                    14,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    55,
                    3,
                    "Keramik figurer",
                    15,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    56,
                    4,
                    "Georg Jensen",
                    1,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    57,
                    4,
                    "Hans Hansen",
                    2,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    58,
                    4,
                    "Anton Michelsen",
                    3,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    59,
                    4,
                    "Armbånd",
                    4,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    60,
                    4,
                    "Brocher",
                    5,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    61,
                    4,
                    "Halskæder & Vedhæng",
                    6,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    62,
                    4,
                    "Ringe",
                    7,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    63,
                    4,
                    "Øreringe",
                    8,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    64,
                    4,
                    "Øvrige smykker",
                    9,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    65,
                    7,
                    "Georg Jensen bestik",
                    1,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    66,
                    7,
                    "Hans Hansen bestik",
                    2,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    67,
                    7,
                    "Arne Jacobsen bestik",
                    3,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    68,
                    7,
                    "Rosenborg bestik",
                    4,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    69,
                    7,
                    "Julebestik Georg Jensen",
                    5,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    70,
                    7,
                    "Julebestik Michelsen",
                    6,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    71,
                    7,
                    "Julebestik Øvrigt",
                    7,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    72,
                    7,
                    "Mindebestik",
                    8,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    73,
                    7,
                    "Andre bestik",
                    9,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    74,
                    8,
                    "Bjørn Wiinblad",
                    1,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    75,
                    8,
                    "Hjorth – Søholm - Michael Andersen",
                    2,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    76,
                    8,
                    "Ipsen",
                    3,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    77,
                    8,
                    "Kähler",
                    4,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    78,
                    8,
                    "Royal Copenhagen - Bing & Grøndahl - Aluminia",
                    5,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    79,
                    8,
                    "Saxbo",
                    6,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    80,
                    8,
                    "Arne bang",
                    7,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    81,
                    8,
                    "Palshus",
                    8,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    82,
                    8,
                    "Øvrig Keramik",
                    9,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    83,
                    9,
                    "Aluminia platter",
                    1,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    84,
                    9,
                    "Bjørn Wiinblad platter",
                    2,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    85,
                    9,
                    "Bing & Grøndahl platter",
                    3,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    86,
                    9,
                    "Royal Copenhagen platter",
                    4,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    87,
                    9,
                    "Forhandlerskilte",
                    5,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    88,
                    9,
                    "Årskrus",
                    6,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    89,
                    13,
                    "Aluminia Julehjerter",
                    1,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    90,
                    13,
                    "Arne Bang keramik",
                    2,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    91,
                    13,
                    "Bjørn Wiinblad",
                    3,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    92,
                    13,
                    "Blå Blomst",
                    4,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    93,
                    13,
                    "Blåmalet",
                    5,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    94,
                    13,
                    "Dahl Jensen figurer ",
                    6,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    95,
                    13,
                    "Danske møbler",
                    7,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    96,
                    13,
                    "Empire stel",
                    8,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    97,
                    13,
                    "Figurer",
                    9,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    98,
                    13,
                    "Flora Danica",
                    10,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    99,
                    13,
                    "Georg Jensen Juleuroer",
                    11,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    100,
                    13,
                    "Georg Jensen sølv",
                    12,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    101,
                    13,
                    "Guld",
                    13,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    102,
                    13,
                    "Henriette",
                    14,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    103,
                    13,
                    "Juleplatter",
                    15,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    104,
                    13,
                    "Kay Bojesen træfigurer",
                    16,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    105,
                    13,
                    "Konkylie stel",
                    17,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    106,
                    13,
                    "Musselmalet",
                    18,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    107,
                    13,
                    "Halvblonde",
                    19,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    108,
                    13,
                    "Helblonde",
                    20,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    109,
                    13,
                    "Måge med & uden guldkant ",
                    21,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    110,
                    13,
                    "Purpur Musselmalet",
                    22,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    111,
                    13,
                    "Saxbo keramik",
                    23,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    112,
                    13,
                    "Sommerfugl",
                    24,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                ),
                (
                    113,
                    13,
                    "Sølv",
                    25,
                    "https://via.placeholder.com/600x400",
                    "Beskrivelse"
                )
            };
        }
    }
}
