# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Stop docker container
      run: docker stop groenlundapicontainer
    - name: Delete docker container
      run: docker rm groenlundapicontainer
    - name: Remove docker image
      run: docker rmi groenlundapiimage    
    - name: Delete docker image
      run: docker image prune -a --force --filter "until=2h"
    - name: Change directory on server
      run: cd ~/actions-runner/_work/DiplomaProject/DiplomaProject/GroenlundAPI/
    - name: Build Docker Image
      run: docker build -t groenlundapiimage -f Dockerfile .
    - name: Run Docker
      run: docker run -d -p 5001:5000 --name groenlundapicontainer groenlundapiimage
