name: CI/CD

on:
  push:
    branches:
      - ISS_Dev

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy to IIS
      run: |
        $env:TARGET_PATH = "C:\inetpub\wwwroot\GroenlundAPI"
        Remove-Item -Path $env:TARGET_PATH -Recurse -Force -ErrorAction Ignore
        Copy-Item -Path .\publish -Destination $env:TARGET_PATH -Recurse -Force
